---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: default
  labels:
    app: redis-master
spec:
  selector:
    matchLabels:
      app: redis-master
      tier: back-end
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
        tier: back-end
    spec:
      containers:
        - name: master-redis-xfusion 
          image: redis:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
              name: redis-master
          restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: default
spec:
  selector:
    app: redis-master
    tier: back-end
  type: ClusterIP
  ports:
    - name: redis-master
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: default
  labels:
    app: redis-slave
    tier: back-end
spec:
  selector:
    matchLabels:
      app: redis-slave
      tier: back-end
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-slave
        tier: back-end
    spec:
      containers:
        - name: slave-redis-xfusion 
          image: gcr.io/google_samples/gb-redisslave:v3
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 6379
              name: redis-slave
          startPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: default
spec:
  selector:
    app: redis-slave
    tier: back-end
  type: ClusterIP
  ports:
    - name: redis-slave
      port: 6379
      targetPort: 6379
