apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-devops
  namespace: default
  labels:
    app: countdown-devops
spec:
  template:
    metadata:
      name: countdown-devops
      labels:
        app: countdown-devops
    spec:
      containers:
      - name: container-countdown-devops
        image: ubuntu:latest
        command: ['sh', '-c', 'for i in 10 9 8 7 6 5 4 3 2 1 ; do echo $i ; done']
      restartPolicy: Never
