apiVersion: v1
kind: CronJob
metadata:
  name: datacenter
spec:
  schedule: "*/4 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-datacenter
            image: nginx:latest
            command: ["sh","-c","echo Welcome to xfusioncorp!"]
          restartPolicy: OnFailure  

