apiVersion: v1
kind: ConfigMap
metadata:
  name: my-redis-config
  namespace: default
data:
  redis-config: |-
    maxmemory 2mb


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis-deployment
  namespace: default
  labels:
    app:  redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app:  redis
    spec:
      containers:
      - name:  redis-container
        image:  redis:alpine
        resources:
          requests:
            cpu: 1
        ports:
        - containerPort:  6379
        volumeMounts:
        - name:  data
          mountPath: /redis-master-data
        - name:  redis-config
          mountPath: /redis-master
      volumes:
        - name: data
          emptyDir: {}
        - name: redis-config
          configMap:
           name: my-redis-config
      restartPolicy: Always
