apiVersion: apps/v1
kind: Deployment
metadata:
  name:  httpd-deploy
  namespace: devops
  labels:
    app:  httpd-deploy
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  httpd
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  httpd
        image:  httpd:2.4.28
        ports:
        - containerPort:  8080
