apiVersion: v1
kind: Namespace
metadata:
  name: httpd-namespace-nautilus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  httpd-deployment-nautilus
  namespace: httpd-namespace-nautilus
  labels:
    app:  httpd-deployment-nautilus
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 2
  template:
    metadata:
      labels:
        app:  httpd
    spec:
      containers:
      - name:  httpd
        image:  httpd:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service-nautilus
  namespace: httpd-namespace-nautilus
spec:
  selector:
    app: httpd
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30004