apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass
  namespace: default
type: Opaque
data:
    password: WVVJaWRoYjY2Nw==

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
  namespace: default
type: Opaque
data:
    username: kodekloud_sam
    password: {{ .Values.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url
  namespace: default
type: Opaque
data:
    database: kodekloud_db4

kubectl create secret generic mysql-root-pass --from-literal=password=YUIidhb667
kubectl create secret generic mysql-user-pass --from-literal=username=kodekloud_tim --from-literal=password=ksH85UJjhb
kubectl create secret generic mysql-db-url --from-literal=database=kodekloud_db7
