apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx-deployment
  type: NodePort
  ports:
  - name: nginx-service
    port: 80
    nodePort: 30011