apiVersion: v1
kind: Pod
metadata:
  name: pod-nautilus
  namespace: default
  labels:
    app: pod-nautilus
spec:
  containers:
  - name: container-nautilus
    image: nginx:latest
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
      - containerPort: 80
    volumeMounts:
    - name: pvc-nautilus
      mountPath: /usr/share/nginx/html
  volumes:
    - name: pvc-nautilus
      persistentVolumeClaim:
        claimName: pvc-nautilus