apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nautilus
  namespace: default
  labels:
    app: pvc-nautilus
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi