apiVersion: v1
kind: Pod
metadata:
  name: secret-devops
  namespace: default
  labels:
    app: "secret-datacenter"
spec:
  volumes:
    - name: secret-volume-devops
      secret:
        secretName: blog
  containers:
    - name: secret-container-devops
      image: centos:latest
      command: ['sh','-c','sleep 10000']
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      volumeMounts:
        - name: secret-devops-official
          readOnly: true
          mountPath: /opt/cluster
  restartPolicy: Always