apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: datacenter
  labels:
    app: time-check
spec:
  containers:
  - name: time-check    
    image: busybox:latest
    command: ['sh','-c','while true; do date; sleep $TIME_FREQ;done > /opt/finance/time/time-check.log']
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: TIME_FREQ
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: "TIME_FREQ"
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: log-volume
      mountPath: /opt/finance/time
  volumes:
    - name: log-volume
      emptyDir: {}
  restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: datacenter
data:
  TIME_FREQ: "5"