apiVersion: v1
kind: Namespace
metadata:
  name: tomcat-namespace-devops
  labels:
    name: tomcat-namespace-devops

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  tomcat-deployment-devops
  namespace: tomcat-namespace-devops
  labels:
    app:  tomcat-deployment-devops
spec:
  selector:
    matchLabels:
      app: tomcat-deployment-devops
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  tomcat-deployment-devops
    spec:
      containers:
      - name:  tomcat-container-devops
        image:  gcr.io/kodekloud/centos-ssh-enabled:tomcat
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-devops
  namespace: tomcat-namespace-devops
spec:
  selector:
    app: tomcat-deployment-devops
  type: NodePort
  ports:
  - name: tomcat-service-devops
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32227
