apiVersion: v1
kind: Pod
metadata:
  name: volume-share-datacenter
  namespace: default
  labels:
    app: volume-share-datacenter
spec:
  containers:
  - name: volume-container-datacenter-1
    image: fedora:latest
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    command: ["sh","-c","sleep 1000"]
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/blog
  - name: volume-container-datacenter-2
    image: fedora:latest
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    command: ["sh","-c","sleep 1000"]
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/cluster    
  volumes:
    - name: volume-share
      emptyDir: {}
  restartPolicy: Always